site_name: Smash 64 modding wiki
site_url: https://joaorb64.github.io/smash64-modding-wiki/
theme:
  name: material
  palette:
    scheme: slate
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - search.suggest
    # - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
plugins:
  - search
  # - git-authors
  - git-committers:
      repository: joaorb64/smash64-modding-wiki
      branch: main
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences