site_name: My Docs
site_url: https://joaorb64.github.io/smash64-modding-wiki/
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: orange
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - search.suggest
    - search.highlight
plugins:
  - search
  - git-authors